[package]
name = "AnimeGo"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
crossterm = "0.27.0"
menu_rs = "0.3.1"
reqwest = {version = "0.12.4", features = ["blocking","json"]}
serde = {version = "1.0.201",features = ["derive"] }
serde_json = "1.0.117"
